jwt:
  issuer-uri: ${JWT_ISSUER_URI}
  jwk-set-uri: ${JWT_JWK_SET_URI}
  auth:
    converter:
      resource-id: ${JWT_AUTH_CONVERTER_RESOURCE_ID}
      principle-attribute: ${JWT_AUTH_CONVERTER_PRINCIPLE_ATTRIBUTE}
  expiration: ${JWT_EXPIRATION}