spring:
  profiles:
    include:
    - security
    - oauthGoogle
    - jwt
    - keycloak
    - rsocket
  application:
    name: ${SPRING_APPLICATION_NAME}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}